version: '3.9'

services:
  app:
    image: 522986700920.dkr.ecr.eu-west-1.amazonaws.com/py-demo:latest
    restart: always
    expose: 
      - 8080
    networks:
      - py-net

  nginx:
    image: nginx:1.25.1-alpine
    container_name: py-proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - py-net
    expose:
      - 80
    ports:
      - 80:80
    
networks:
  py-net:
